// Generated by delombok at Fri Mar 17 11:01:30 UTC 2023
package fr.univtln.bruno.demos.jpa.hello;

import fr.univtln.bruno.demos.jpa.hello.samples.Customer02;
import jakarta.persistence.EntityManager;

import java.io.IOException;
import java.time.LocalDate;

/**
 * Main class.
 */
public class Main {
    @java.lang.SuppressWarnings("all")
    private static final java.util.logging.Logger log = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Main method.
     *
     * @param args
     * @throws IOException
     */
    public static void main(String[] args) {
        try (EntityManager entityManager = DatabaseManager.emf.createEntityManager()) {
            Customer02 customer02 = Customer02.of("pierre.durand@ici.fr");
            entityManager.persist(customer02);
            log.info(customer02.toString());
            customer02.setBirthDate(LocalDate.of(2012, 3, 5));
            entityManager.merge(customer02);
            log.info(customer02.toString());
        }
    }
}
