// Generated by delombok at Fri Mar 17 11:01:30 UTC 2023
package fr.univtln.bruno.demos.jpa.hello.samples;

import jakarta.persistence.*;
import lombok.*;

@Entity
public class Customer01 {
    @Id
    @NonNull
    private long id;
    @NonNull
    private String email;
    private String firstname;
    private String lastname;

    @java.lang.SuppressWarnings("all")
    public Customer01(@NonNull final long id, @NonNull final String email) {
        if (email == null) {
            throw new java.lang.NullPointerException("email is marked non-null but is null");
        }
        this.id = id;
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    protected Customer01() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Customer01)) return false;
        final Customer01 other = (Customer01) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getId() != other.getId()) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$firstname = this.getFirstname();
        final java.lang.Object other$firstname = other.getFirstname();
        if (this$firstname == null ? other$firstname != null : !this$firstname.equals(other$firstname)) return false;
        final java.lang.Object this$lastname = this.getLastname();
        final java.lang.Object other$lastname = other.getLastname();
        if (this$lastname == null ? other$lastname != null : !this$lastname.equals(other$lastname)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Customer01;
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    public long getId() {
        return this.id;
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getFirstname() {
        return this.firstname;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastname() {
        return this.lastname;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastname(final String lastname) {
        this.lastname = lastname;
    }

    @java.lang.SuppressWarnings("all")
    public void setFirstname(final String firstname) {
        this.firstname = firstname;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(@NonNull final String email) {
        if (email == null) {
            throw new java.lang.NullPointerException("email is marked non-null but is null");
        }
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(@NonNull final long id) {
        this.id = id;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $id = this.getId();
        result = result * PRIME + (int) ($id >>> 32 ^ $id);
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $firstname = this.getFirstname();
        result = result * PRIME + ($firstname == null ? 43 : $firstname.hashCode());
        final java.lang.Object $lastname = this.getLastname();
        result = result * PRIME + ($lastname == null ? 43 : $lastname.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Customer01(id=" + this.getId() + ", email=" + this.getEmail() + ", firstname=" + this.getFirstname() + ", lastname=" + this.getLastname() + ")";
    }
}
